spring.application.name=mcp-server
server.port=1631

#?????
spring.datasource.url=jdbc:mysql://192.168.19.129:3306/local_helper?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

management.endpoints.web.exposure.include=*
spring.mvc.converters.preferred-json-mapper=jack

spring.main.web-application-type=servlet
spring.ai.mcp.server.name=weather-service
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.type=async
spring.ai.mcp.server.sse-message-endpoint=/mcp/sse
spring.ai.mcp.server.resource-change-notification=true
spring.ai.mcp.server.prompt-change-notification=true
spring.ai.mcp.server.tool-change-notification=true


# 网络搜索
spring.ai.mcp.web-search.endpoint=https://serpapi.com/search
spring.ai.mcp.web-search.api-key=<API_KEY>
spring.jackson.time-zone=Asia/Shanghai

# 天气查询
spring.ai.mcp.weather-search.endpoint=https://api.seniverse.com/v3/weather/daily.json?
spring.ai.mcp.weather-search.api-key=<API_KEY>

# 百度地理位置查询
spring.ai.mcp.location-search.endpoint=https://api.map.baidu.com/location/ip?coor=bd09ll&ak=
# 百度天气查询
spring.ai.mcp.weather-search-baidu.endpoint=https://api.map.baidu.com/weather/v1/?
spring.ai.mcp.location-search.api-key=<API_KEY>
